
site_name: SSC Tool Guide
site_url: https://jackwharrison.github.io/ssc-tool/
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - toc:
        permalink : true
        permalink_title: Specific link to this section
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - privacy
  - search
  - glightbox

theme:
    name: material
    language: en
    palette:
      primary: custom
    logo: assets/img/510Logo.png
    favicon: assets/img/favicon.ico
    features:
      - navigation.top
      - navigation.instant
      - navigation.instant.progress

extra:
  generator: false
#   alternate:
#     - name: English
#       link: /
#       lang: en
#     - name: Nederlands
#       link: /nl/
#       lang: nl

nav:
    - 'Home': 'index.md'
    - 'General': 
      - 'Intro to the SSC': 'general/page1.md'
      - 'Pillar 1 - The Shelter': 'general/page2.md'
      - 'Pillar 2 - Inside The Shelter': 'general/page3.md'
      - 'Pillar 3 - Outside The Shelter': 'general/page4.md'
    - 'Administrative Divisions':
      - 'Administrative Regions': 'administrative_regions/page1.md'
    - 'Indicators and Decisions Trees' :
      - 'Indicator Bank': 'indicators_and_decision_trees/page1.md'
      - 'Hazard Indicators': 'indicators_and_decision_trees/page2.md'
      - 'Decision Trees': 'indicators_and_decision_trees/page3.md'
    - ' Data (Pillars, Vulnerabilities, Hazards, and Impacts)' :
      - 'Data': 'data/page1.md'
    - ' Visualizations' :
      - 'Visualizations': 'visualizations/page1.md'    
    - 'Customization': 
      - 'How to create a new entity': 'customization/page1.md'
      - 'How to link entities': 'customization/page2.md'
      - 'Sending SMS messages': 'customization/page3.md'
      - 'Mass messaging with WhatsApp/Twilio': 'customization/page4.md'
      - 'DEH': 'customization/page5.md'
      - 'Sending emails': 'customization/page6.md'
      - 'Integration of EspoCRM with KoboToolbox ': 'customization/page7.md'
      - 'Integration of EspoCRM with Twilio': 'customization/page8.md'
      - 'Creating dashboards in EspoCRM': 'customization/page10.md'
      - 'Flowcharts': 'customization/page11.md'
    - 'Advanced Pack':
      - 'Advanced Pack License': 'advanced/page1.md'

    
